CREATE TABLE ALUNO ( 
    MATRICULA INT,
    NOME VARCHAR(45),
    CPF INT,
    IDENTIDADE VARCHAR(20),
    TELEFONE INT
);
CREATE TABLE FAMILIARES_ALUNO (
    MATRICULA INT,
    NOME_FAMILIAR VARCHAR(45),
    GRAU_PARENTESCO VARCHAR(10),
    VINCULO_EMPREGATICIO BOOLEAN,
    RENDA MENSAL MONEY
);
CREATE TABLE ENDERECO (
    MATRICULA INT,
    RUA VARCHAR(45),
    NUMERO INT,
    CIDADE VARCHAR(45),
    ESTADO VARCHAR(45)
);

CREATE TABLE EVASAO_DIFICULDADES (
	MATRICULA INT,
    DISCIPLINA VARCHAR(45),
    DIFICULDADES VARCHAR (45)
);
CREATE TABLE ASSISTENCIA_TRANSPORTE_MODALIDADE_PRETENDIDA (
    MATRICULA INT,
    TIPO VARCHAR(45)
);
CREATE TABLE ASSISTENCIA (
	MATRICULA INT,
    DOCUMENTACAO BLOB
);    
CREATE TABLE ASSISTENCIA_AUXILIOS (
    MATRICULA INT,
    ALIMENTACAO BOOLEAN,
    TRANSPORTE BOOLEAN,
    MORADIA BOOLEAN,
    DIDATICO BOOLEAN
);
CREATE TABLE ASSISTENCIA_ALUNOS_PENDENCIA_DOCUMENTOS (
	MATRICULA INT,
	DOCUMENTO_PENDENTE VARCHAR(45)
); 

CREATE TABLE AUXILIO_TRANSPORTE
(
    MODALIDADE VARCHAR(50)
	DESCRICAO VARCHAR(50)
);

CREATE TABLE AUXILIO_ALIMENTACAO
(
    MODALIDADE VARCHAR(50)
	DESCRICAO VARCHAR(50)
);

CREATE TABLE AUXILIO_MORADIA
(
    MODALIDADE VARCHAR(50)
	DESCRICAO VARCHAR(50)
);

CREATE TABLE DISCIPLINAS
(
    DISCPLINA VARCHAR(50)
);

CREATE TABLE EVASAO_QUADRO_DIFICULDADES
(
    MATRICULA VARCHAR(20)
	HORA_INICIO TIME
	HORA_FIM TIME
	DIA_SEMANA DAY
	ATIVIDADE VARCHAR(50)
);

CREATE TABLE ALUNOS_INTERESSADOS_PARTICIPAR_ASSISTENFCIA
(
	MATRICULA VARCHAR(20)
);

CREATE TABLE ALUNOS_JA_PARTICIPANTES_ASSISTENCIA
(
	MATRICULA VARCHAR(20)
);

CREATE TABLE DOCUMENTOS_COMPROBATORIOS
(
    MODALIDADE VARCHAR(50)
	DESCRICAO VARCHAR(50)
);




